<?php

namespace MNHcC;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-16 at 23:40:56.
 */
class ModuleTest extends \Zend\Test\PHPUnit\Controller {

    /**
     * @var Module
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Module;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MNHcC\Module::onBootstrap
     * @todo   Implement testOnBootstrap().
     */
    public function testOnBootstrap() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MNHcC\Module::getViewHelperConfig
     * @todo   Implement testGetViewHelperConfig().
     */
    public function testGetViewHelperConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
